spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: user
    password: password
    port: 587
    debug: true
    template: email-template.txt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false